### PR TITLE
🔭

### PR DESCRIPTION
**Pull request by 0xhealer**
Hello,
I have been using this theme for my neovim setup recently and wanted to create one for my Windows Terminal too. So decided to add it to the repo directly. Do check it out and let me know!

Thank You :)

### CODE REVIEW

**Comment by jaredgorski** [comment]
Thanks for sending, @techtuner!

The only addition needed is to the README, specifically the **Terminal emulator themes** section: https://github.com/jaredgorski/SpaceCamp#terminal-emulator-themes

Would you mind adding an entry in the list under that section to the README as part of this PR? The list is sorted alphanumerically ascending.

After that, I think this PR is good to go 😃

**Comment by techtuner** [comment]
Can you walk me through how to pull the pushed commit back please😅. Sorry I'm jut learning this so I'm not o good at this

**Comment by jaredgorski** [comment]
No need to reset any commits, you can just add a new one with the README change on top. No worries!

**Comment by 0xhealer** [comment]
@jaredgorski  There is a small typo in the comment section if possible can you please fix that 

```diff
- 1. Go to Windows Settings and Open JSON file
+ 1. Go to Windows Terminal Settings and Open JSON file
```

sorry missed that while adding it
 Regards,
Santhosh

**Comment by jaredgorski** [comment]
Will do

**Comment by 0xhealer** [comment]
Thank You :)

**Pull request merged**
